# Change these first
owner: terablitz # Your GitHub organization or username, where this repository lives
repo: ranwalk-uptime # The name of this repository

sites:
  - name: Ranwalk main
    url: https://app.ranwalk.com

status-website:
  baseUrl: /ranwalk-uptime # where "repo" is your repository name
  name: is ranwalk up?
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
